name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Dotnet setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version : 6.0.x

      - name: Install dotnet tools
        run: |
          dotnet tool install -g BundlerMinifier.Core

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: /home/runner/work/.net-ci-cd/.net-ci-cd/UploadFilesServer/bin/Debug/net6.0/publish/

      - name: Zip artifact for deployment
        run: zip build.zip ./* -r

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts