name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Dotnet setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version : 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: /home/runner/work/.net-ci-cd/.net-ci-cd/UploadFilesServer/bin/Debug/net6.0/publish/

      - name: Zip artifact for deployment
        run: zip  ./build.zip /home/runner/work/.net-ci-cd/.net-ci-cd/UploadFilesServer/bin/Debug/net6.0/publish/* -r

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: escape

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz /home/runner/work/.net-ci-cd/.net-ci-cd/UploadFilesServer/bin/Debug/net6.0/publish/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/All_Updates/Oct31/test/

      - name: Publish the Code
        run: |
          TIMESTAMP=`date +%Y%m%d-%H%M%S`
          sudo cp /var/www/api/gittest /var/www/api/gittest_$TIMESTAMP/ -r
          echo 'backup created'
          sudo mv /var/www/api/gittest_* /var/www/api/Backup
          echo 'backup moved'
          sudo cp /home/ubuntu/All_Updates/Oct31/test/* /var/www/api/gittest/ -r
          echo 'update files copied'
          cat /var/www/api/testapi/appsettings.json
          echo 'appsetting available'
          sudo chown nginx.nginx /var/www/api/testapi/* -R
          sudo chmod 755 /var/www/api/testapi/* -R
        shell: bash